### ISSUE TITLE
Inserir o Awesome badge

### ISSUE THREAD

**Issue by rogeriopradoj** [30contribs/awesome-contribs-br#2]
https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge

**Comment by ghost** [comment]
What's this issue about?

**Comment by rogeriopradoj** [comment]
Hi, @Tchinmai7 , this issue is to just add the **awesome badge** in this **awesome list**, right?

This list is very pointed to be used by Brazilians (that's the reason of the suffix -br).

Anyway, you are very welcome to help us, ok?

Thank you!
